//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poject_md
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_workshops
    {
        public int id { get; set; }
        public int id_product { get; set; }
        public int id_workshop { get; set; }
        public int time_m_ { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Workshops Workshops { get; set; }
    }
}
