//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poject_md
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Product_workshops = new HashSet<Product_workshops>();
        }
    
        public int id { get; set; }
        public int type_products_id { get; set; }
        public string name_product { get; set; }
        public string articul { get; set; }
        public double min_cost_seller { get; set; }
        public int base_material_id { get; set; }

        public string TimeModule
        {  get
            {
                int time = 0;
                foreach (var item in Product_workshops)
                {
                    time += item.time_m_;
                }
                return time.ToString() + " ч";
            } }
    
        public virtual Material_type Material_type { get; set; }
        public virtual Product_type Product_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_workshops> Product_workshops { get; set; }
    }
}
